# Generated by Django 3.2.5 on 2021-09-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20210919_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='career',
        ),
    ]
