# Generated by Django 3.2.5 on 2021-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
