# Generated by Django 3.2.5 on 2021-09-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_portfolio_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Designs',
        ),
    ]
