# Generated by Django 3.2.5 on 2021-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_auto_20210921_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksample',
            name='title',
        ),
        migrations.AddField(
            model_name='worksample',
            name='icon',
            field=models.ImageField(default='static/img/work1.jpg', upload_to='picture/'),
        ),
    ]
